apiVersion: apps/v1
kind: Deployment
metadata:
  name: prete-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prete-service
  template:
    metadata:
      labels:
        app: prete-service
    spec:
      containers:
        - name: prete-service
          image: prete-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_APPLICATION_NAME
              value: PRETE-SERVICE
            - name: SERVER_PORT
              value: "8081"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-db:3306/biblio_prete?createDatabaseIfNotExist=true
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://discovery-service:8761/eureka
            - name: LECTEUR_SERVICE_URL
              value: http://lecteur-service:8083
            - name: LIVRE_SERVICE_URL
              value: http://livre-service:8080
---
apiVersion: v1
kind: Service
metadata:
  name: prete-service
spec:
  selector:
    app: prete-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP